package it.gov.pagopa.pu.registry.enums;

public enum EventType {
  DP_CREATED,
  DP_UPDATED,
  DP_CANCELLED,
  DPI_ADDED,
  DPI_CANCELLED,
  DPI_UPDATED,
  DPI_EXPIRED,
  DPI_REPORTED,
  RT_RECEIVED,
  SYNC_ERROR,
  IO_NOTIFIED,
  SEND_NOTIFICATION_CREATED,
  SEND_NOTIFICATION_ERROR,
  SEND_NOTIFICATION_DATE
}
